_version = 1

[workflow]
graph = "../../docs/internal/demo/01-hello.fabro"

[run.pull_request]
enabled = false

[run.run_branch]
enabled = false

[run.meta_branch]
enabled = false

[run.environment]
id = "docker"
